apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: block-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: gateway
          image: ghcr.io/noa-beyond/gateway:v1.1.8
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/logs
              name: block-ssd-storage
            - name: config-volume
              mountPath: /app/config/appsettings.json
              subPath: appsettings_gateway.json
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka1:9092,kafka2:9092,kafka3:9092"
            - name: TOPIC
              value: "gateway.order.requested"
            - name: GROUP_ID
              value: "test-consumer-group"
      volumes:
        - name: config-volume
          configMap:
            name: gateway-config
        - name: block-ssd-storage
          persistentVolumeClaim:
            claimName: gateway-pvc
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

