apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-bastion
  labels:
    app: bastion
spec:
  containers:
    - name: ubuntu
      image: rastasheep/ubuntu-sshd:18.04
      ports:
        - containerPort: 22
      volumeMounts:
        - name: ssh-keys
          mountPath: /root/.ssh/authorized_keys
          subPath: authorized_keys
  volumes:
    - name: ssh-keys
      secret:
        secretName: ssh-key-secret
---          
apiVersion: v1
kind: Service
metadata:
  name: bastion-service
spec:
  type: NodePort
  selector:
    app: bastion
  ports:
    - port: 22
      targetPort: 22
      nodePort: 32222 
